### ISSUE TITLE
v11

### ISSUE THREAD

**Issue by brunocalado** [jdeon/foundryVTT-pinned-chatlog-module#11]
Great module.

Can you make it ready for v11?

tks

**Comment by jdeon** [comment]
Thank you.

Normally the version 1.3.0 work on v11.
Do you mean to change the verified version ?

**Comment by brunocalado** [comment]
Yes. Changing it to "11" will remove the warning.

Em qua, 7 de jun de 2023 18:25, jdeon ***@***.***> escreveu:

**Comment by brunocalado** [comment]
thank you
