### ISSUE TITLE
Create a setting to rename "Pinned"

### ISSUE THREAD

**Issue by brunocalado** [jdeon/foundryVTT-pinned-chatlog-module#12]
Hi.

Can you add a setting option to rename "Pinned"? This would allow to easily translate and also define this tab to some specific use.
![image](https://github.com/jdeon/foundryVTT-pinned-chatlog-module/assets/4999783/1b3a2cc7-6606-4bc4-8774-41d64876f661)

tks

**Comment by jdeon** [comment]
If it a localisation problem, you can add an translation in `languages/`

I m not convinced to add settings to change a label. What kind of use are you thinking about ?

**Comment by brunocalado** [comment]
> If it a localisation problem, you can add an translation in `languages/`
> 
> I m not convinced to add settings to change a label. What kind of use are you thinking about ?

This would allow to define the reason to pin a message. Example: you only pin the current roll message to allow the players to pick options to roll without be annoyed by the group messages. The tab name would be "Roll Dice" or something. This allow you to rename it to make clear the purpose.

**Comment by jdeon** [comment]
Not convinced to prioritize this feature, I see it more like a other module using mine to pinned all roll dice. In that case, the module can rename the tab.
Have you see the module "Tabbed Chatlog", I inspired myself from and it seem to meet your needs better than me.

If you have time for this, you can do a pull request and I accept it.

**Comment by brunocalado** [comment]
> Tabbed Chatlog

Thank you. I'll take a look.
