### ISSUE TITLE
API Hook

### ISSUE THREAD

**Issue by brunocalado** [jdeon/foundryVTT-pinned-chatlog-module#13]
Hi.

Can you add an API call or a procedure to allow module creators to add as pinned a message on creation?

Example: a module will create a chat message for a roll, when this module send the message to the chat, the message will show up already pinned.

tks

**Comment by jdeon** [comment]
I'm going to think about it.

For now, the simple way to do it, is add a flag : `chatMessage.flags.pinnedChat.pinned = true`
