### ISSUE TITLE
Player should be able to self pin any message [Feature Request]

### ISSUE THREAD

**Issue by kiloforce** [jdeon/foundryVTT-pinned-chatlog-module#37]
A player may want to save a message for reference later.  But the GM may not want the player accidentally filling up the "Pinned" window with pinned messages.  So feature request is the player should be able to "self" pin any messages, not just their own messages.  In fact, as the GM, I would prefer if the default were all pinned messages were self pinned, including my own.  Maybe reverse the logic so that single click self pins, and double click public pins?

**Comment by jdeon** [comment]
I'm not sure to do a breaking change for one issue.
But I will think about adding a settings to choose the behaviour.

**Comment by jdeon** [comment]
The "Minimal role to pin others' messages" settings is firstly technical. Are you allow the player to update an unowned chat message data ? So it would be the same for self pinned.
Currently, I see this options : 
1. Setting to choose if you want that the click pinned for all or self pinned
2. Setting "Minimal role to self pin others' messages" and if you re not allow to self and all pinned the behaviour is the same either in simple or double click (Seems probably to complex)
3. Settings to disable pinned for all and/or self pinned behaviour (for player or for all ?). It would also affect owned message (Fastest change)

**Comment by jdeon** [comment]
With no reply, I will do the third option.

**Comment by kiloforce** [comment]
Sorry for the late response.  In my opinion, users should only ever be able to "self pin", but they should be able to "self pin" any message.

**Comment by jdeon** [comment]
It's now possible by allowing the player role to update unowned message and disable "pin for all" for player.

**Comment by kiloforce** [comment]
Thanks
