### ISSUE TITLE
Add a "pin" feature to the "right click" context menu [Feature Request]

### ISSUE THREAD

**Issue by kiloforce** [jdeon/foundryVTT-pinned-chatlog-module#38]
There is another module that can "pin" messages, but I like how this one organizes pinned messages better.  The one thing I liked that the other one did is you could pin messages using a right click on the message (in the context menu).  The tiny "pin" is harder to click than the larger area that the right click can land on, and as a GM when I have many many things to focus on every second is important.  Kindly add a "pin" and "unpin" to the right click context menu for the messages.  Thanks!

**Comment by jdeon** [comment]
Great idea.

**Comment by jdeon** [comment]
Done, release in the next version

**Comment by kiloforce** [comment]
Thank you
