### ISSUE TITLE
Feature: Merge features with "dfreds-chat-pins"

### ISSUE THREAD

**Issue by tagnullde** [jdeon/foundryVTT-pinned-chatlog-module#43]
Hey,

I like your mod and this module seems to be better maintained too.
However, [dfreds-chat-pins](https://github.com/DFreds/dfreds-chat-pins) has some cool features I would be grateful to see here too.

An option to exclude pinned messages from being deleted during "main chat" clearing would be the main one. 
And maybe the "jump to pin" feature. 

Thanks for considering it. 

x41

**Comment by jdeon** [comment]
Hello,
I like the idea to protect the pinned message from delete all, I will add a setting in the next version.
But I am not convinced of the "jump to pin" feature.

**Comment by tagnullde** [comment]
Sound good to me. Thank you. :)

**Comment by jdeon** [comment]
Release in v2.2.0
