### ISSUE TITLE
"Protect pinned messages from deletion" didn't work (v12)

### ISSUE THREAD

**Issue by MothMariner** [jdeon/foundryVTT-pinned-chatlog-module#46]
Potentially/probably a v12 thing, but "protect pinned messages from deletion" didn't work when I tried it in v12.

**Comment by jdeon** [comment]
Thanks, I will try v12 this week to see.

**Comment by jdeon** [comment]
Yes options.deleteAll seems to not be send any more in the hooks.
I need to find another solution.

**Comment by jdeon** [comment]
I create an issue on Foundry (https://github.com/foundryvtt/foundryvtt/issues/11310).
They said it's a intentional change so I will change the feature to block every deletion from GM of pinned message

**Comment by jdeon** [comment]
Done in version 2.2.1
